# Generated by Django 5.0.6 on 2026-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=30)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('change_1h', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('change_24h', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('change_7d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('ath', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('rank', models.PositiveIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['symbol'], name='crypto_pric_symbol_b08be8_idx'), models.Index(fields=['rank'], name='crypto_pric_rank_acd3f5_idx')],
            },
        ),
    ]
