# Generated by Django 5.0.6 on 2026-03-18 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('description_vi', models.TextField(blank=True)),
                ('token_symbol', models.CharField(blank=True, max_length=20)),
                ('total_allocation', models.CharField(blank=True, max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('airdrop_type', models.CharField(choices=[('free', 'Free Airdrop'), ('task', 'Task-based'), ('holder', 'Holder Airdrop'), ('testnet', 'Testnet')], default='task', max_length=20)),
                ('requirements', models.JSONField(default=list)),
                ('guide_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Sắp diễn ra'), ('active', 'Đang diễn ra'), ('ended', 'Đã kết thúc')], default='upcoming', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='airdrops_ai_status_a4993c_idx'), models.Index(fields=['airdrop_type', 'status'], name='airdrops_ai_airdrop_3a110c_idx')],
            },
        ),
    ]
