# Generated by Django 5.0.6 on 2026-03-18 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('rss_url', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('crawl_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('title_vi', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('summary_vi', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('original_url', models.URLField(unique=True)),
                ('ai_summarized', models.BooleanField(default=False)),
                ('ai_translated', models.BooleanField(default=False)),
                ('ai_tags_generated', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='en', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='published', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newssource')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['status', '-published_at'], name='news_articl_status_dad29a_idx'), models.Index(fields=['category', '-published_at'], name='news_articl_categor_32b688_idx')],
            },
        ),
    ]
